### ISSUE TITLE
Masks for `🭲` and `🭹` are wrong

### ISSUE THREAD

**Issue by yvt** [lf94/png2linetext#4]
`🭲`uses `🭹`'s mask and vice versa. 

https://github.com/lf94/img2utf/blob/6b73d75c38220ff6708f466254a6d7a83f69af36/src/main.rs#L48-L49

https://github.com/lf94/img2utf/blob/6b73d75c38220ff6708f466254a6d7a83f69af36/src/main.rs#L177-L186

**Comment by lf94** [comment]
Ah yeah, thanks!

**Comment by lf94** [comment]
Resolved
