### ISSUE TITLE
How to save output to a png file?

### ISSUE THREAD

**Issue by Honghe** [lf94/png2linetext#5]
For  ASCII art, there is a tool https://github.com/ansilove/ansilove to save the output as a png file.
So how to save img2utf output, which contains non ASCII chars, to a png file?

**Comment by lf94** [comment]
You could use `imagemagick`'s `convert` command to print the text:

`convert -background white -fill black -font 'a font which supports all the necessary glyphs' label:@the-file-containing-the-text output.png`

**Comment by lf94** [comment]
That's what I'm doing for my use-case: 

![is-privacy-in-our-evolutionary-interest txt](https://user-images.githubusercontent.com/547923/106892423-0d6b0600-66ba-11eb-809f-23fb9c62d7b4.png)

**Comment by lf94** [comment]
I'm using FairfaxSMHD.ttf font.

**Comment by Honghe** [comment]
@lf94 I still have problem of converting with “ width or height exceeds limit”.
```
MAGICK_WIDTH_LIMIT=200MP MAGICK_HEIGHT_LIMIT=200MP convert -background white -fill black -font 'UbuntuMono-R.ttf' label:@p.ansi output.png
convert-im6.q16: width or height exceeds limit `@p.ansi' @ error/label.c/ReadLABELImage/138.
convert-im6.q16: no images defined `output.png' @ error/convert.c/ConvertImageCommand/3258.
```
p.ansi file content:
![image](https://user-images.githubusercontent.com/1092722/106907643-70e84880-6739-11eb-9428-6e0467aa9f04.png)

**Comment by Honghe** [comment]
@lf94 How can I know  which fonts support all the necessary glyphs?

**Comment by lf94** [comment]
Any font which supports the Symbols for Legacy Computing block. The font I wrote supports it. :slightly_smiling_face: 

That error you hit is because of Imagemagick policy, located somewhere in `/etc/`. Remove the policy about width. I think policies exist to prevent imagemagick from exceeding certain memory restrictions and other things.
